# Name of workflow
name: Development build

# When workflow is triggered
on: [pull_request]

jobs:
  build:
    # Operating system to run job on
    runs-on: ubuntu-latest
    # Steps in job
    steps:
      - name: Wait for Netlify Deploy
        uses: probablyup/wait-for-netlify-action@3.2.0
        id: waitForDeployment
        with:
          site_id: ${{ secrets.NETLIFY_SITE_ID }}
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
